version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:

  ## Switch
  central-ledger:
    image: mojaloop/central-ledger:${CENTRAL_LEDGER_VERSION}
    container_name: central-ledger
    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/central-ledger.js /opt/app/config/default.json && /opt/app/wait4/wait4.js central-ledger && node src/api/index.js"
    ports:
      - "3001:3001"
    volumes:
       - ./docker/wait4:/opt/app/wait4
       - ./docker/config-modifier:/opt/app/config-modifier
    environment:
      - LOG_LEVEL=info
      - CLEDG_MONGODB__DISABLED=false
    networks:
      - mojaloop-net
    depends_on:
      mysql:
        condition: service_started
      kafka:
        condition: service_started
      objstore:
        condition: service_started
    healthcheck:
      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 30s
      start_period: 30s
    user: root
    profiles:
      - central-ledger
      - transfer
      - discovery
      - agreement
      - all-services

  objstore:
    image: mongo:${DEP_MONGO_VERSION}
    container_name: objstore
    ports:
      - "27017:27017"
    networks:
      - mojaloop-net
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - central-ledger
      - transfer
      - discovery
      - agreement
      - all-services

  kafka-provisioning:
    container_name: kafka-provisioning
    networks:
      - mojaloop-net
    image: docker.io/bitnami/kafka:${DEP_KAFKA_VERSION}
    depends_on:
      - kafka
    volumes:
      - ./docker/kafka/scripts:/tmp/kafka/scripts
    command: bash /tmp/kafka/scripts/provision.sh
    profiles:
      - central-ledger
      - transfer
      - discovery
      - agreement
      - all-services

  kafka:
    networks:
      - mojaloop-net
    image: docker.io/bitnami/kafka:${DEP_KAFKA_VERSION}
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # BITNAMI_DEBUG: "yes"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093,LISTENER_DOCKER://kafka:29092,LISTENER_EXTERN://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_EXTERN://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_DOCKER:PLAINTEXT,LISTENER_EXTERN:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_MESSAGE_MAX_BYTES: 200000000
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_ENABLE_KRAFT: "true"
    healthcheck:
      test: ["CMD" ,"/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh","--bootstrap-server","kafka:9092"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    profiles:
      - central-ledger
      - transfer
      - discovery
      - agreement
      - all-services

  mysql:
    image: mysql/mysql-server:${DEP_MYSQL_VERSION}
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      # Note: this fixes the permissions issue, but docker-compose up will fail on first attempt
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-central_ledger}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-central_ledger}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    profiles:
      - central-ledger
      - transfer
      - discovery
      - agreement
      - all-services

  quoting-service:
    image: "mojaloop/quoting-service:${QUOTING_SERVICE_VERSION}"
    container_name: quoting-service
    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/quoting-service.js /opt/app/config/default.json && node src/index.js"
    networks:
      - mojaloop-net
    depends_on:
      mysql:
        condition: service_started
      central-ledger:
        condition: service_started
    ports:
      - "3002:3002"
    volumes:
      - ./docker/config-modifier:/opt/app/config-modifier
    healthcheck:
      test: wget -q http://localhost:3002/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    user: root
    profiles:
      - quoting-service
      - agreement
      - all-services

  ml-api-adapter:
    image: mojaloop/ml-api-adapter:${ML_API_ADAPTER_VERSION}
    container_name: ml-api-adapter
    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/ml-api-adapter.js /opt/app/config/default.json && /opt/app/wait4/wait4.js ml-api-adapter && node src/api/index.js"
    ports:
      - "3000:3000"
    volumes:
      - ./docker/wait4:/opt/app/wait4
      - ./docker/config-modifier:/opt/app/config-modifier
    environment:
      - LOG_LEVEL=info
    networks:
      - mojaloop-net
    depends_on:
      kafka:
        condition: service_started
      central-ledger:
        condition: service_started
    healthcheck:
      test: wget -q http://localhost:3000/health -O /dev/null || exit 1
      timeout: 30s
      retries: 30
      interval: 30s
      start_period: 30s
    user: root
    profiles:
      - ml-api-adapter
      - transfer
      - all-services

  simulator:
    image: mojaloop/simulator:${TEST_SIMULATOR_VERSION}
    container_name: simulator
    ports:
      - "8444:8444"
    environment:
      - LOG_LEVEL=info
      - TRANSFERS_ENDPOINT=http://ml-api-adapter:3000
      - QUOTES_ENDPOINT=http://quoting-service:3002
      - PARTIES_ENDPOINT=http://account-lookup-service:4002
      - TRANSACTION_REQUESTS_ENDPOINT=http://transaction-request-service:4003
      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://localhost:8444/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      interval: 30s
    profiles:
      - simulator
      - discovery
      - all-services

  account-lookup-service:
    image: twstm/account-lookup-service:${ACCOUNT_LOOKUP_SERVICE_VERSION}
    container_name: account-lookup-service
    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/account-lookup-service.js /opt/app/config/default.json && /opt/app/wait4/wait4.js account-lookup-service && npm run migrate && node src/index.js server"
    ports:
      - "4001:4001"
      - "4002:4002"
    environment:
      - LOG_LEVEL=info
      - ALS_DISPLAY_ROUTES=false
      - EVENT_SDK_TRACEID_PER_VENDOR=false
    networks:
      - mojaloop-net
    depends_on:
      mysql-als:
        condition: service_started
      central-ledger:
        condition: service_started
    volumes:
      - ./docker/wait4:/opt/app/wait4
      - ./docker/config-modifier:/opt/app/config-modifier
    healthcheck:
      test: wget -q http://localhost:4001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    user: root
    profiles:
      - account-lookup-service
      - discovery
      - all-services

  mysql-als:
    image: mysql/mysql-server:${DEP_MYSQL_VERSION}
    container_name: mysql-als
    # ports:
    #   - "3307:3306"
    volumes:
      - ./docker/sql-als-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-account_lookup}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-account_lookup}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-als"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    profiles:
      - account-lookup-service
      - discovery
      - all-services

  ## Testing Toolkit
  mojaloop-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:${TEST_TTK_SVC_VERSION}
    volumes:
      - "./docker/ml-testing-toolkit/spec_files:/opt/app/spec_files"
      - "./docker/ml-testing-toolkit/test-cases:/opt/app/examples"
    ports:
      - "9440:4040"
      - "9550:5050"
    user: root
    command:
      - sh
      - -c
      - "npm start"
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD-SHELL", "nc -z -v localhost 4040"]
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 10
    profiles:
      - testing-toolkit
      - all-services

  mojaloop-testing-toolkit-ui:
    image: twstm/ml-testing-toolkit-ui:${TEST_TTK_UI_VERSION}
    ports:
      - "9660:6060"
    environment:
      - API_BASE_URL=http://localhost:9550
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh
    networks:
      - mojaloop-net
    profiles:
      - testing-toolkit
      - all-services

  ttk-provisioning:
    image: mojaloop/ml-testing-toolkit-client-lib:${TEST_TTK_CLI_VERSION}
    volumes:
      - "./docker/ml-testing-toolkit/test-cases/collections:/opt/app/collections"
      - "./docker/ml-testing-toolkit/test-cases/environments:/opt/app/environments"
      - "./reports:/opt/app/reports"
    depends_on:
      mojaloop-testing-toolkit:
        condition: service_healthy
      central-ledger:
        condition: service_healthy
      ml-api-adapter:
        condition: service_healthy
      account-lookup-service:
        condition: service_healthy
      quoting-service:
        condition: service_healthy
    networks:
      - mojaloop-net
    command:
      - sh
      - -c
      - "npm run cli -- -u http://mojaloop-testing-toolkit:5050 -l 2 -i collections/provisioning -e environments/default-env.json --save-report true --report-format html --report-target file://reports/ttk-provisioning-report.html"
    user: root
    profiles:
      - ttk-provisioning

  ttk-tests:
    image: mojaloop/ml-testing-toolkit-client-lib:${TEST_TTK_CLI_VERSION}
    volumes:
      - "./docker/ml-testing-toolkit/test-cases/collections:/opt/app/collections"
      - "./docker/ml-testing-toolkit/test-cases/environments:/opt/app/environments"
      - "./reports:/opt/app/reports"
    depends_on:
      mojaloop-testing-toolkit:
        condition: service_healthy
      central-ledger:
        condition: service_healthy
      ml-api-adapter:
        condition: service_healthy
      account-lookup-service:
        condition: service_healthy
      quoting-service:
        condition: service_healthy
      ttk-provisioning:
        condition: service_completed_successfully
    networks:
      - mojaloop-net
    command:
      - sh
      - -c
      - "npm run cli -- -u http://mojaloop-testing-toolkit:5050 -l 2 -i collections/tests -e environments/default-env.json --report-format html --save-report true --report-target file://reports/ttk-func-tests-report.html"
    user: root
    profiles:
      - ttk-tests

  ## Debug utilities
  kafka-debug-ui:
    image: docker.redpanda.com/redpandadata/console:${DEP_KAfKA_UI_VERSION}
    deploy:
      replicas: 1
    restart: on-failure
    hostname: kafka-debug-ui
    ports:
      - "8080:8080"
    networks:
      - mojaloop-net
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    profiles:
      - debug

  acquirer-backend:
    container_name: acquirer-backend
    image: twstm/acquirer-backend:${MERCHANT_ACQUIRER_BACKEND_VERSION}
    networks:
      - mojaloop-net
    command: ["npm", "run", "acquirer-backend:start"]
    ports:
      - "5555:5555"
    environment:
      - APP_URL=http://0.0.0.0:5555
      - HOST=0.0.0.0
      - PORT=5555

      - DB_HOST=acquirer-db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=merchant_acquirer_db

      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_MERCHANT_BUCKET_NAME=merchant-documents

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest # TODO: change this in production
      - RABBITMQ_PASSWORD=guest # TODO: change this in production
      - RABBITMQ_QUEUE=acquirer_to_registry
      - RABBITMQ_REPLY_QUEUE=registry_reply_acquirer
      # - SENDGRID_API_KEY=<sendgrid-api> # TODO: change this 

    profiles:
      - merchant-services
      - all-services

    depends_on:
      - acquirer-db
      - minio
      - rabbitmq

  acquirer-frontend:
    image: twstm/acquirer-frontend:${MERCHANT_ACQUIRER_FRONTEND_VERSION}
    container_name: acquirer-frontend
    networks:
      - mojaloop-net
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - VITE_API_URL=http://localhost:5555/api/v1
    ports:
      - "5173:5173"

    profiles:
      - merchant-services
      - all-services


  registry-oracle:
    image: twstm/registry-oracle:${MERCHANT_REGISTRY_ORACLE_VERSION}
    container_name: registry-oracle
    healthcheck:
      test: wget -q http://localhost:6666/health-check -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    networks:
      - mojaloop-net
    ports:
      - 6666:6666
    environment:
      - APP_URL=http://0.0.0.0:6666
      - HOST=0.0.0.0
      - PORT=6666

      - DB_HOST=oracle-db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=registry-oracle

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest # TODO: change this in production
      - RABBITMQ_PASSWORD=guest # TODO: change this in production
      - RABBITMQ_QUEUE=acquirer_to_registry
      - RABBITMQ_REPLY_QUEUE=registry_reply_acquirer

    depends_on:
      - oracle-db
      - rabbitmq
      # oracle-db:
      #   condition: service_healthy
      # rabbitmq:
      #   condition: service_healthy
          

    profiles:
      - merchant-services
      - all-services


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.4-management-alpine
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - mojaloop-net
    ports:
      - 5673:5672 
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest # TODO: change this in production
      - RABBITMQ_DEFAULT_PASS=guest # TODO: change this in production
    profiles:
      - merchant-services
      - all-services


  acquirer-db:
    container_name: acquirer-db
    networks:
      - mojaloop-net
    image: mysql:8.0.33
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=merchant_acquirer_db
    ports:
      - 8808:3306
    profiles:
      - merchant-services
      - all-services


  oracle-db:
    container_name: oracle-db
    networks:
      - mojaloop-net
    image: mysql:8.0.33
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registry-oracle
    ports:
      - 7707:3306
    profiles:
      - merchant-services
      - all-services


  minio:
    networks:
      - mojaloop-net
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data

    profiles:
      - merchant-services
      - all-services

volumes:
  data:

